
package testgenviewsemiautomatico.repository;
/**
* Generated by CESSOFT
* Copyright (C) 2013 
*/

import junit.framework.TestSuite;
import junit.extensions.TestSetup;
import java.io.File;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/**
* Test suite for the complete package.
*/
public final class Sample1PackageTestSuite {

/**
* Local object of Sample1LogTestCase class.
*/
    private static Sample1LogTestCase log;

/**
* Notifies if excluded file of failed
* test cases exits.
*/
    public static boolean excludeFileExists = false;

/**
* A variable to keep count of successful.
* test cases.
*/
    public static int totalTestCases = 0;

/**
* Private Constructor of the test suite class.
*/
    private Sample1PackageTestSuite() {
    }

/**
* Set-Up method for the test suite.

* @return
*         Returns the test suite set-up.
*/
    public static TestSetup suite() {

    TestSuite suite;

    suite = new TestSuite("All Packages");

    suite.addTestSuite(Sample1Test.class);

      TestSetup wrapper = new TestSetup(suite) {

          protected void setUp() {
              File failedXMLDataFile = new File(
              "C:\\Users\\tpbm68\\Documents\\TesisProject\\TestGentView\\src\\testgenviewsemiautomatico\\repository\\", "failedData.xml");
              File logFile = new File("C:\\Users\\tpbm68\\Documents\\TesisProject\\TestGentView\\src\\testgenviewsemiautomatico\\repository\\", "TestFailure.log");

              if (logFile.exists()) {
                  logFile.delete();
                  try {
                      log.createFailedTestLog("C:\\Users\\tpbm68\\Documents\\TesisProject\\TestGentView\\src\\testgenviewsemiautomatico\\repository\\");
                  } catch (Exception e) {
                      e.printStackTrace();
                  }
              }

              if (failedXMLDataFile.exists()) {
                  excludeFileExists = true;
              } else if (!failedXMLDataFile.exists()) {
                  try {
                      log.createFailedXMLDataFile("C:\\Users\\tpbm68\\Documents\\TesisProject\\TestGentView\\src\\testgenviewsemiautomatico\\repository\\");
                  } catch (Exception e) {
                      e.printStackTrace();
                  }
              }
          }

/**
* Wrap-Up method for the test suite.
*/
          protected void tearDown() {
              File logFile = new File("C:\\Users\\tpbm68\\Documents\\TesisProject\\TestGentView\\src\\testgenviewsemiautomatico\\repository\\", "TestSuccess.log");

              try {
                      BufferedWriter out = new BufferedWriter(new
                         FileWriter(logFile, true));
                      out.newLine();
                      out.write("Total test cases executed: " + totalTestCases);
                      out.newLine();
                      out.newLine();
                      out.flush();
                      out.close();
              } catch (IOException e) {
                   e.printStackTrace();
              }

            if (!excludeFileExists) {
              try {
                  log.endFailedXMLDataFile("C:\\Users\\tpbm68\\Documents\\TesisProject\\TestGentView\\src\\testgenviewsemiautomatico\\repository\\");
                  excludeFileExists = true;
              } catch (Exception e) {
                   e.printStackTrace();
              }
            }
          }
      };

      return wrapper;
  }

/**
* Main method of the test suite.

* @param args
*            Stores arguments to main method
*/
  public static void main(final String[] args) {
    // Begin method testsuite.main
    junit.textui.TestRunner.run(suite());
    // End method testsuite.main
  }
}
